FROM docker.io/library/alpine:3.18@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a

# toolchain
RUN apk add --no-cache llvm16 clang16 clang16-extra-tools
RUN apk add --no-cache libc++ libc++-dev libc++-static compiler-rt musl-dev
RUN apk add --no-cache make

# boost deps
RUN apk add --no-cache linux-headers

# libboost
RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.bz2 \
    && tar --bzip2 -xf boost_1_82_0.tar.bz2 \
    && cd boost_1_82_0/ \
    && ./bootstrap.sh --with-toolset=clang --without-icu \
    && ./b2 \
      toolset=clang \
      cxxflags="-std=c++2b -stdlib=libc++" \
      linkflags="-stdlib=libc++ -lc++abi" \
      variant=release \
      debug-symbols=off \
      threading=multi \
      runtime-link=static \
      link=static \
      --with-filesystem \
      --with-url \
      install \
    && cd .. && rm -rf boost_1_82_0*

# liblz4
RUN wget https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz \
    && tar xzf lz4-1.9.4.tar.gz \
    && cd lz4-1.9.4/ \
    && CC=clang make \
    && CC=clang make install \
    && cd .. && rm -rf lz4-1.9.4*

# project tools
RUN apk add --no-cache cmake pkgconf ninja-build ninja-is-really-ninja lf ccache

# project deps: libarchive, openssl
RUN apk add --no-cache libarchive-dev libarchive-static acl-static zlib-static xz-static bzip2-static expat-static zstd-static
RUN apk add --no-cache openssl-dev openssl-libs-static
