#!/usr/bin/env bash

make_docker_proj()
{
  podman build -f docker/Dockerfile.proj -t tvenv:proj
}

make_docker_stage0()
{
  podman build -f docker/Dockerfile.stage0 -t tvenv:stage0
}

make_docker_stage1()
{
  podman build -f docker/Dockerfile.stage1 -t tvenv:stage1
}

cmake()
{
  podman run -it -v ./:/proj:Z -w /proj tvenv:proj cmake -B build-out -S . -G Ninja --fresh
}

build()
{
  podman run -it -v ./:/proj:Z -w /proj tvenv:proj cmake --build build-out
}

run0()
{
  podman run -it -v ~/tcroot:/tcroot:Z -v ./build-out:/proj:Z -w /proj tvenv:stage0 ./tcenv s0
}

run1()
{
  podman run -it -v ~/tcroot:/tcroot:Z -v ./build-out:/proj:Z -w /proj tvenv:stage1 ./tcenv s1
}

all()
{
  build
  run0
  run1
}

${1}